### ISSUE TITLE
D8-govcms template fails since composer is v1

### ISSUE THREAD

**Issue by gilzow** [platformsh/template-builder#659]
Several of the composer dependencies are locked to v2 of composer API, the current version will fail to deploy. Suggest adding 

```yaml
dependencies:
  php:
    composer/composer: '^2'
```
to .platform.app.yaml
