### ISSUE TITLE
Templates mention the Legacy CLI

### ISSUE THREAD

**Issue by lolautruche** [platformsh/template-builder#695]
Templates like [the one for Drupal 9](https://github.com/platformsh/template-builder/blob/master/templates/drupal9/platformsh.wizard.yaml#L16) still mention the old fashioned way of installing the CLI.
We should update the instructions in order to ensure people are using the latest CLI: https://docs.platform.sh/administration/cli.html

What we currently have:

```yaml
    copyCode:
      - label: "macOS and Linux Installer"
        code:
          - "curl -sS https://platform.sh/cli/installer | php"
      - label: "Windows Installer"
        code:
          - "curl https://platform.sh/cli/installer -o cli-installer.php"
          - "php cli-installer.php"
```

What we should have:

```yaml
    copyCode:
      - label: "macOS and Linux Installer (using Homebrew)"
        code:
          - "brew install platformsh/tap/platformsh-cli"
      - label: "Windows Installer (using Scoop)"
        code:
          - "scoop bucket add platformsh https://github.com/platformsh/homebrew-tap.git"
          - "scoop install platform"
```
